### ISSUE TITLE
zerohub client should be part of std jumpscale

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/sandbox#4]
why?

pip3 install -e 'git+https://github.com/zero-os/0-hub#egg=zerohub&subdirectory=client'

for all other components we wrap in jumpscale, so why should we not do this for our own components?
Or you wrap & then the pip3 should be done when installing js93
Or you have the client in js93 in the code repo itself

**Comment by ahussein** [comment]
the hub client is only used to merge  the generated flist with a base ubuntu flist, so its not really part of the sandboxing process for js9.
We can for sure include it when creating the js9 sandbox as well.

**Comment by zaibon** [comment]
This has nothing to do with your sandboxing process.
Problem is the zero-hub client code is out of jumpscale and this is wrong.
It should be included into jumspcale lib9 like any other client

**Comment by ahussein** [comment]
I will move this to lib9 repository.

**Comment by ahussein** [comment]
duplicate of https://github.com/Jumpscale/lib9/issues/249
