### ISSUE TITLE
sandbox has nothing to do with adding an ubuntu flist to it !!!!

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/sandbox#5]
the python3 & js93 sandbox can be run directly from the directory which was sandboxed
with nothing more than doing

```
source $theSBdir/env.sh
js9
```

there is no integration with ubuntu or chroot required at all !!!

the ubuntu you will need if you want to run as full blown container in zero-os.
But then it should be

- you create flist for the sandbox
- you can test the flist of the sandbox using the bundle tool
- you can now merge with ubuntu flist
- you can now start in container as follows (NOT CHROOT!!!)

```
source $theSBdir/env.sh
js9
```

**Comment by ahussein** [comment]
we already generate two flist:
- sandbox_js9.flist contains only js9/python3.6 
- sandbox_js9_full.flist is a merge between sandbox_js9.flist and a base ubuntu flist

So both are there, anyone interested can use the one they need.
