### ISSUE TITLE
/etc/resolv.conf should contain proper nameserver out of the box

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/sandbox#6]
In the documentation I see:
```
echo "nameserver 8.8.8.8" > /etc/resolv.conf; source env.sh;....
```
This shouldn't be needed, the sandox is supposed to be ready out of the box. During buidling, replace the nameserver with proper one before creating the flist.

at the moment `resolve.conf` contains
```
# Generated by dhcpcd from eth0.dhcp
# /etc/resolv.conf.head can replace this line
domain home.maxux.net
nameserver 10.241.0.254
# /etc/resolv.conf.tail can replace this line
```

**Comment by ahussein** [comment]
This is related to how the Ubuntu flist was created. Nothing to do with the js9 and python sandbox.

Need to check who created that flsit and if there an automated script to create it so that we can change that script if already exists
