### ISSUE TITLE
capacity checker doesn't work from the sandbox

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/sandbox#7]
Install the zbundle and start the sandbox as documented:
```
zbundle -id js9sandbox --entry-point /bin/bash --no-exit https://hub.gig.tech/abdelrahman_hussein_1/js9_sandbox_full.flist
```
Then
```
source env.sh
report = j.sal.ubuntu.capacity.report()
```
and got this error:

```
RuntimeError: 
Could not execute:    apt-get install dmidecode --force-yes -y

stdout:
    Reading package lists...
    Building dependency tree...
    The following NEW packages will be installed:
      dmidecode
    0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.

stderr:
    /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
    W: --force-yes is deprecated, use one of the options starting with --allow instead.
    E: Can't find a source to download version '3.0-2' of 'dmidecode:amd64'
```

So I see 2 issues here.
- Installing should not even be needed, the sandbox should have all the required binaries and component included.
- Why is the installation fails ? bug in the code of the capacity checker itself ?

**Comment by ahussein** [comment]
I dont know why the capacity SAL was developed this way that it need to install a binary when it  runs. Will check the tool and fix if needed.

**Comment by zaibon** [comment]
It needs to have dmidcode and smartctl to be able to work, so it first check if these binaries exists and if not install them. How else would you do it ?

**Comment by FastGeert** [comment]
I think we better add the right binaries to the sandbox immediatly.

**Comment by ahussein** [comment]
Yes. I am preparing an Ubuntu flist that contians the required binaries

**Comment by zaibon** [comment]
> I think we better add the right binaries to the sandbox immediatly.

exactly what I said in my first post

> Installing should not even be needed, the sandbox should have all the required binaries and component included.

**Comment by ahussein** [comment]
According to @rkhamis KDS wants to have these binaries in a different flist

**Comment by rkhamis** [comment]
Yes, so let's create a separate flist for capacity checker which would be merged with the sandbox before running

**Comment by ahussein** [comment]
Latest flist from https://hub.gig.tech/abdelrahman_hussein_1/js9_sandbox_full.flist contains the binaries for dmidecode and smartctl
New flist for capacity checker has been created and can be found here: https://hub.gig.tech/abdelrahman_hussein_1/capacity_checker_js9.flist

**Comment by ahussein** [comment]
@islamTaha12 validate the new flists
